### PR TITLE
Add hc10dt moveit config

### PR DESCRIPTION
**Pull request by mark-toma**
Will leave this open while adding gazebo support and integration of moveit_planning_execution.launch with the gazebo simulation.

### CODE REVIEW

**Comment by mark-toma** [comment]
@araman92: Stay tuned for gazebo integration...

**Comment by mark-toma** [comment]
This HC10DT support for MoveIt! includes the `moveit_planning_execution` launch file which enables control of the real robot (using `motoman_driver`) or a simulated robot using a controller named `hc10dt_arm_controller`. A Gazebo support package for HC10DT just needs to be based on the URDF file for the HC10DT from `motoman_hc10_support` and provide an appropriately named controller to be driven by this `moveit_planning_execution` launch file.

Usage (simulated robot):

```
$ # launch simulated robot providing hc10dt_arm_controller
$ roslaunch motoman_hc10dt_moveit_config moveit_planning_execution.launch
```

**Comment by adhitir** [comment]
Did you write that package or are you basing it on an existing example?

**Comment by mark-toma** [comment]
The basic `motoman_hc10dt_moveit_config` package was made using the Moveit! Setup Assistant in f1e5da68. Then in 0788cfd8 I used the same utility to remove an end effector group I created but didn't need. I thought that would confuse matters. Then e9eaa1d3 added the `moveit_planning_execution` launch file. This is the one you can use to connect to a real robot or a simulated robot. It's configured to connect to the controllers defined in #3.

**Pull request merged**
